name: sonarqube

on:
  push:
  pull_request:  
  workflow_dispatch:

jobs:
  sonarqube_analysis:
    name: SonarQube analysis
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4

      - name: Setup frontend analysis environment (install NodeJS)
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Setup frontend analysis environment (install libraries)
        run: npm ci --force
        working-directory: ./frontend

      - name: Setup backend analysis environment (install Java)
        uses: actions/setup-java@v4
        with:
            java-version: '21'
            distribution: 'temurin'
            cache: maven
      
      - name: Print keytool version
        run: $JAVA_HOME/bin/keytool -version
      
      # Installs "calibre" and "pandoc" libraries
      # They are required to run unit tests
      - name: Setup backend analysis environment (install Linux libs)
        run: sudo apt-get update && sudo apt-get install -y libopengl0 libxcb-cursor0 libegl1
      - name: Setup backend analysis environment (install Calibre)
        run: sudo -v && wget -nv -O- https://download.calibre-ebook.com/linux-installer.sh | sudo sh /dev/stdin          
      - name: Setup backend analysis environment (install Pandoc)
        run: wget https://github.com/jgm/pandoc/releases/download/3.3/pandoc-3.3-1-amd64.deb && sudo dpkg -i pandoc-3.3-1-amd64.deb
        working-directory: /tmp
      
      - name: Setup backend analysis environment (configure Github Packages access)
        uses: s4u/maven-settings-action@v3.0.0
        with:
          servers: '[{"id": "github","configuration": {"httpHeaders": {"property": {"name": "Authorization","value": "Bearer ${{ secrets.GITHUB_TOKEN }}"}}}}]'

      - name: Setup backend analysis environment (build JAR)
        run: mvn clean verify
        working-directory: ./backend

      - name: Setup analysis dependencies
        run: sudo apt-get install -y jq curl openssl
        working-directory: ./scripts

      - name: Download SonarScanner
        run: |
          wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-6.2.1.4610-linux-x64.zip
          unzip sonar-scanner-cli-6.2.1.4610-linux-x64.zip
        
      - name: Setup SonarQube environment variables
        run: |

      - name: Run SonarQube analysis
        run: |
          export EBW_SONAR_TOKEN_BACKEND="${{ secrets.EBW_SONAR_TOKEN_BACKEND }}"
          export EBW_SONAR_TOKEN_FRONTEND="${{ secrets.EBW_SONAR_TOKEN_FRONTEND }}"
          chmod a+x ./sonarqube-run.sh
          chmod a+x ../backend/mvnw
          sudo -E PATH=$PATH:${{ github.workspace }}/sonar-scanner-6.2.1.4610-linux-x64/bin ./sonarqube-run.sh
        working-directory: ./scripts
      
      - name: Upload SonarQube report
        run: |
          export EBW_SONAR_CREDENTIALS="${{ secrets.EBW_SONAR_CREDENTIALS }}"
          export EBW_INFLUXDB_TOKEN="${{ secrets.EBW_INFLUXDB_TOKEN }}"
          chmod a+x ./sonarqube-influxdb-push.sh
          sudo -E ./sonarqube-influxdb-push.sh
        working-directory: ./scripts
